apiVersion: v1
kind: ServiceAccount
metadata:
  name: iot-operator
  namespace: iot-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iot-operator
  namespace: iot-system
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iot-operator
  namespace: iot-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iot-operator
subjects:
- kind: ServiceAccount
  name: iot-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iot-operator
rules:
- apiGroups:
  - "iot.thetechnick.ninja"
  resources:
  - rollershutters
  - rollershutters/status
  - rollershutters/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iot-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iot-operator
subjects:
- kind: ServiceAccount
  name: iot-operator
  namespace: iot-system
